/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkapaRouteImport } from './routes/skapa'
import { Route as GlennRouteImport } from './routes/glenn'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UtforskaIndexRouteImport } from './routes/utforska/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UtforskaSportRouteImport } from './routes/utforska/$sport'
import { Route as TackTransactionIdRouteImport } from './routes/tack/$transactionId'
import { Route as SShopSlugRouteImport } from './routes/s/$shopSlug'
import { Route as AdminShopIdRouteImport } from './routes/admin/$shopId'
import { Route as SShopSlugIndexRouteImport } from './routes/s/$shopSlug/index'
import { Route as AdminShopIdIndexRouteImport } from './routes/admin/$shopId/index'
import { Route as SShopSlugQrRouteImport } from './routes/s/$shopSlug/qr'
import { Route as SShopSlugKlartRouteImport } from './routes/s/$shopSlug/klart'
import { Route as AdminShopIdSkyltRouteImport } from './routes/admin/$shopId/skylt'
import { Route as AdminShopIdSettingsRouteImport } from './routes/admin/$shopId/settings'
import { Route as AdminShopIdProductsRouteImport } from './routes/admin/$shopId/products'
import { Route as AdminShopIdHistorikRouteImport } from './routes/admin/$shopId/historik'
import { Route as UtforskaSportCityIndexRouteImport } from './routes/utforska/$sport/$city/index'

const SkapaRoute = SkapaRouteImport.update({
  id: '/skapa',
  path: '/skapa',
  getParentRoute: () => rootRouteImport,
} as any)
const GlennRoute = GlennRouteImport.update({
  id: '/glenn',
  path: '/glenn',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UtforskaIndexRoute = UtforskaIndexRouteImport.update({
  id: '/utforska/',
  path: '/utforska/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const UtforskaSportRoute = UtforskaSportRouteImport.update({
  id: '/utforska/$sport',
  path: '/utforska/$sport',
  getParentRoute: () => rootRouteImport,
} as any)
const TackTransactionIdRoute = TackTransactionIdRouteImport.update({
  id: '/tack/$transactionId',
  path: '/tack/$transactionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SShopSlugRoute = SShopSlugRouteImport.update({
  id: '/s/$shopSlug',
  path: '/s/$shopSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShopIdRoute = AdminShopIdRouteImport.update({
  id: '/admin/$shopId',
  path: '/admin/$shopId',
  getParentRoute: () => rootRouteImport,
} as any)
const SShopSlugIndexRoute = SShopSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SShopSlugRoute,
} as any)
const AdminShopIdIndexRoute = AdminShopIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminShopIdRoute,
} as any)
const SShopSlugQrRoute = SShopSlugQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => SShopSlugRoute,
} as any)
const SShopSlugKlartRoute = SShopSlugKlartRouteImport.update({
  id: '/klart',
  path: '/klart',
  getParentRoute: () => SShopSlugRoute,
} as any)
const AdminShopIdSkyltRoute = AdminShopIdSkyltRouteImport.update({
  id: '/skylt',
  path: '/skylt',
  getParentRoute: () => AdminShopIdRoute,
} as any)
const AdminShopIdSettingsRoute = AdminShopIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminShopIdRoute,
} as any)
const AdminShopIdProductsRoute = AdminShopIdProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminShopIdRoute,
} as any)
const AdminShopIdHistorikRoute = AdminShopIdHistorikRouteImport.update({
  id: '/historik',
  path: '/historik',
  getParentRoute: () => AdminShopIdRoute,
} as any)
const UtforskaSportCityIndexRoute = UtforskaSportCityIndexRouteImport.update({
  id: '/$city/',
  path: '/$city/',
  getParentRoute: () => UtforskaSportRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/glenn': typeof GlennRoute
  '/skapa': typeof SkapaRoute
  '/admin/$shopId': typeof AdminShopIdRouteWithChildren
  '/s/$shopSlug': typeof SShopSlugRouteWithChildren
  '/tack/$transactionId': typeof TackTransactionIdRoute
  '/utforska/$sport': typeof UtforskaSportRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/utforska': typeof UtforskaIndexRoute
  '/admin/$shopId/historik': typeof AdminShopIdHistorikRoute
  '/admin/$shopId/products': typeof AdminShopIdProductsRoute
  '/admin/$shopId/settings': typeof AdminShopIdSettingsRoute
  '/admin/$shopId/skylt': typeof AdminShopIdSkyltRoute
  '/s/$shopSlug/klart': typeof SShopSlugKlartRoute
  '/s/$shopSlug/qr': typeof SShopSlugQrRoute
  '/admin/$shopId/': typeof AdminShopIdIndexRoute
  '/s/$shopSlug/': typeof SShopSlugIndexRoute
  '/utforska/$sport/$city': typeof UtforskaSportCityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/glenn': typeof GlennRoute
  '/skapa': typeof SkapaRoute
  '/tack/$transactionId': typeof TackTransactionIdRoute
  '/utforska/$sport': typeof UtforskaSportRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/utforska': typeof UtforskaIndexRoute
  '/admin/$shopId/historik': typeof AdminShopIdHistorikRoute
  '/admin/$shopId/products': typeof AdminShopIdProductsRoute
  '/admin/$shopId/settings': typeof AdminShopIdSettingsRoute
  '/admin/$shopId/skylt': typeof AdminShopIdSkyltRoute
  '/s/$shopSlug/klart': typeof SShopSlugKlartRoute
  '/s/$shopSlug/qr': typeof SShopSlugQrRoute
  '/admin/$shopId': typeof AdminShopIdIndexRoute
  '/s/$shopSlug': typeof SShopSlugIndexRoute
  '/utforska/$sport/$city': typeof UtforskaSportCityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/glenn': typeof GlennRoute
  '/skapa': typeof SkapaRoute
  '/admin/$shopId': typeof AdminShopIdRouteWithChildren
  '/s/$shopSlug': typeof SShopSlugRouteWithChildren
  '/tack/$transactionId': typeof TackTransactionIdRoute
  '/utforska/$sport': typeof UtforskaSportRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/utforska/': typeof UtforskaIndexRoute
  '/admin/$shopId/historik': typeof AdminShopIdHistorikRoute
  '/admin/$shopId/products': typeof AdminShopIdProductsRoute
  '/admin/$shopId/settings': typeof AdminShopIdSettingsRoute
  '/admin/$shopId/skylt': typeof AdminShopIdSkyltRoute
  '/s/$shopSlug/klart': typeof SShopSlugKlartRoute
  '/s/$shopSlug/qr': typeof SShopSlugQrRoute
  '/admin/$shopId/': typeof AdminShopIdIndexRoute
  '/s/$shopSlug/': typeof SShopSlugIndexRoute
  '/utforska/$sport/$city/': typeof UtforskaSportCityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/glenn'
    | '/skapa'
    | '/admin/$shopId'
    | '/s/$shopSlug'
    | '/tack/$transactionId'
    | '/utforska/$sport'
    | '/admin'
    | '/utforska'
    | '/admin/$shopId/historik'
    | '/admin/$shopId/products'
    | '/admin/$shopId/settings'
    | '/admin/$shopId/skylt'
    | '/s/$shopSlug/klart'
    | '/s/$shopSlug/qr'
    | '/admin/$shopId/'
    | '/s/$shopSlug/'
    | '/utforska/$sport/$city'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/glenn'
    | '/skapa'
    | '/tack/$transactionId'
    | '/utforska/$sport'
    | '/admin'
    | '/utforska'
    | '/admin/$shopId/historik'
    | '/admin/$shopId/products'
    | '/admin/$shopId/settings'
    | '/admin/$shopId/skylt'
    | '/s/$shopSlug/klart'
    | '/s/$shopSlug/qr'
    | '/admin/$shopId'
    | '/s/$shopSlug'
    | '/utforska/$sport/$city'
  id:
    | '__root__'
    | '/'
    | '/glenn'
    | '/skapa'
    | '/admin/$shopId'
    | '/s/$shopSlug'
    | '/tack/$transactionId'
    | '/utforska/$sport'
    | '/admin/'
    | '/utforska/'
    | '/admin/$shopId/historik'
    | '/admin/$shopId/products'
    | '/admin/$shopId/settings'
    | '/admin/$shopId/skylt'
    | '/s/$shopSlug/klart'
    | '/s/$shopSlug/qr'
    | '/admin/$shopId/'
    | '/s/$shopSlug/'
    | '/utforska/$sport/$city/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GlennRoute: typeof GlennRoute
  SkapaRoute: typeof SkapaRoute
  AdminShopIdRoute: typeof AdminShopIdRouteWithChildren
  SShopSlugRoute: typeof SShopSlugRouteWithChildren
  TackTransactionIdRoute: typeof TackTransactionIdRoute
  UtforskaSportRoute: typeof UtforskaSportRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  UtforskaIndexRoute: typeof UtforskaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skapa': {
      id: '/skapa'
      path: '/skapa'
      fullPath: '/skapa'
      preLoaderRoute: typeof SkapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glenn': {
      id: '/glenn'
      path: '/glenn'
      fullPath: '/glenn'
      preLoaderRoute: typeof GlennRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utforska/': {
      id: '/utforska/'
      path: '/utforska'
      fullPath: '/utforska'
      preLoaderRoute: typeof UtforskaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utforska/$sport': {
      id: '/utforska/$sport'
      path: '/utforska/$sport'
      fullPath: '/utforska/$sport'
      preLoaderRoute: typeof UtforskaSportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tack/$transactionId': {
      id: '/tack/$transactionId'
      path: '/tack/$transactionId'
      fullPath: '/tack/$transactionId'
      preLoaderRoute: typeof TackTransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$shopSlug': {
      id: '/s/$shopSlug'
      path: '/s/$shopSlug'
      fullPath: '/s/$shopSlug'
      preLoaderRoute: typeof SShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$shopId': {
      id: '/admin/$shopId'
      path: '/admin/$shopId'
      fullPath: '/admin/$shopId'
      preLoaderRoute: typeof AdminShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$shopSlug/': {
      id: '/s/$shopSlug/'
      path: '/'
      fullPath: '/s/$shopSlug/'
      preLoaderRoute: typeof SShopSlugIndexRouteImport
      parentRoute: typeof SShopSlugRoute
    }
    '/admin/$shopId/': {
      id: '/admin/$shopId/'
      path: '/'
      fullPath: '/admin/$shopId/'
      preLoaderRoute: typeof AdminShopIdIndexRouteImport
      parentRoute: typeof AdminShopIdRoute
    }
    '/s/$shopSlug/qr': {
      id: '/s/$shopSlug/qr'
      path: '/qr'
      fullPath: '/s/$shopSlug/qr'
      preLoaderRoute: typeof SShopSlugQrRouteImport
      parentRoute: typeof SShopSlugRoute
    }
    '/s/$shopSlug/klart': {
      id: '/s/$shopSlug/klart'
      path: '/klart'
      fullPath: '/s/$shopSlug/klart'
      preLoaderRoute: typeof SShopSlugKlartRouteImport
      parentRoute: typeof SShopSlugRoute
    }
    '/admin/$shopId/skylt': {
      id: '/admin/$shopId/skylt'
      path: '/skylt'
      fullPath: '/admin/$shopId/skylt'
      preLoaderRoute: typeof AdminShopIdSkyltRouteImport
      parentRoute: typeof AdminShopIdRoute
    }
    '/admin/$shopId/settings': {
      id: '/admin/$shopId/settings'
      path: '/settings'
      fullPath: '/admin/$shopId/settings'
      preLoaderRoute: typeof AdminShopIdSettingsRouteImport
      parentRoute: typeof AdminShopIdRoute
    }
    '/admin/$shopId/products': {
      id: '/admin/$shopId/products'
      path: '/products'
      fullPath: '/admin/$shopId/products'
      preLoaderRoute: typeof AdminShopIdProductsRouteImport
      parentRoute: typeof AdminShopIdRoute
    }
    '/admin/$shopId/historik': {
      id: '/admin/$shopId/historik'
      path: '/historik'
      fullPath: '/admin/$shopId/historik'
      preLoaderRoute: typeof AdminShopIdHistorikRouteImport
      parentRoute: typeof AdminShopIdRoute
    }
    '/utforska/$sport/$city/': {
      id: '/utforska/$sport/$city/'
      path: '/$city'
      fullPath: '/utforska/$sport/$city'
      preLoaderRoute: typeof UtforskaSportCityIndexRouteImport
      parentRoute: typeof UtforskaSportRoute
    }
  }
}

interface AdminShopIdRouteChildren {
  AdminShopIdHistorikRoute: typeof AdminShopIdHistorikRoute
  AdminShopIdProductsRoute: typeof AdminShopIdProductsRoute
  AdminShopIdSettingsRoute: typeof AdminShopIdSettingsRoute
  AdminShopIdSkyltRoute: typeof AdminShopIdSkyltRoute
  AdminShopIdIndexRoute: typeof AdminShopIdIndexRoute
}

const AdminShopIdRouteChildren: AdminShopIdRouteChildren = {
  AdminShopIdHistorikRoute: AdminShopIdHistorikRoute,
  AdminShopIdProductsRoute: AdminShopIdProductsRoute,
  AdminShopIdSettingsRoute: AdminShopIdSettingsRoute,
  AdminShopIdSkyltRoute: AdminShopIdSkyltRoute,
  AdminShopIdIndexRoute: AdminShopIdIndexRoute,
}

const AdminShopIdRouteWithChildren = AdminShopIdRoute._addFileChildren(
  AdminShopIdRouteChildren,
)

interface SShopSlugRouteChildren {
  SShopSlugKlartRoute: typeof SShopSlugKlartRoute
  SShopSlugQrRoute: typeof SShopSlugQrRoute
  SShopSlugIndexRoute: typeof SShopSlugIndexRoute
}

const SShopSlugRouteChildren: SShopSlugRouteChildren = {
  SShopSlugKlartRoute: SShopSlugKlartRoute,
  SShopSlugQrRoute: SShopSlugQrRoute,
  SShopSlugIndexRoute: SShopSlugIndexRoute,
}

const SShopSlugRouteWithChildren = SShopSlugRoute._addFileChildren(
  SShopSlugRouteChildren,
)

interface UtforskaSportRouteChildren {
  UtforskaSportCityIndexRoute: typeof UtforskaSportCityIndexRoute
}

const UtforskaSportRouteChildren: UtforskaSportRouteChildren = {
  UtforskaSportCityIndexRoute: UtforskaSportCityIndexRoute,
}

const UtforskaSportRouteWithChildren = UtforskaSportRoute._addFileChildren(
  UtforskaSportRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GlennRoute: GlennRoute,
  SkapaRoute: SkapaRoute,
  AdminShopIdRoute: AdminShopIdRouteWithChildren,
  SShopSlugRoute: SShopSlugRouteWithChildren,
  TackTransactionIdRoute: TackTransactionIdRoute,
  UtforskaSportRoute: UtforskaSportRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  UtforskaIndexRoute: UtforskaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
