/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkapaRouteImport } from './routes/skapa'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TackTransactionIdRouteImport } from './routes/tack/$transactionId'
import { Route as SShopSlugRouteImport } from './routes/s/$shopSlug'
import { Route as RedigeraShopIdRouteImport } from './routes/redigera/$shopId'

const SkapaRoute = SkapaRouteImport.update({
  id: '/skapa',
  path: '/skapa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TackTransactionIdRoute = TackTransactionIdRouteImport.update({
  id: '/tack/$transactionId',
  path: '/tack/$transactionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SShopSlugRoute = SShopSlugRouteImport.update({
  id: '/s/$shopSlug',
  path: '/s/$shopSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const RedigeraShopIdRoute = RedigeraShopIdRouteImport.update({
  id: '/redigera/$shopId',
  path: '/redigera/$shopId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/skapa': typeof SkapaRoute
  '/redigera/$shopId': typeof RedigeraShopIdRoute
  '/s/$shopSlug': typeof SShopSlugRoute
  '/tack/$transactionId': typeof TackTransactionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/skapa': typeof SkapaRoute
  '/redigera/$shopId': typeof RedigeraShopIdRoute
  '/s/$shopSlug': typeof SShopSlugRoute
  '/tack/$transactionId': typeof TackTransactionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/skapa': typeof SkapaRoute
  '/redigera/$shopId': typeof RedigeraShopIdRoute
  '/s/$shopSlug': typeof SShopSlugRoute
  '/tack/$transactionId': typeof TackTransactionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/skapa'
    | '/redigera/$shopId'
    | '/s/$shopSlug'
    | '/tack/$transactionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/skapa'
    | '/redigera/$shopId'
    | '/s/$shopSlug'
    | '/tack/$transactionId'
  id:
    | '__root__'
    | '/'
    | '/skapa'
    | '/redigera/$shopId'
    | '/s/$shopSlug'
    | '/tack/$transactionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SkapaRoute: typeof SkapaRoute
  RedigeraShopIdRoute: typeof RedigeraShopIdRoute
  SShopSlugRoute: typeof SShopSlugRoute
  TackTransactionIdRoute: typeof TackTransactionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skapa': {
      id: '/skapa'
      path: '/skapa'
      fullPath: '/skapa'
      preLoaderRoute: typeof SkapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tack/$transactionId': {
      id: '/tack/$transactionId'
      path: '/tack/$transactionId'
      fullPath: '/tack/$transactionId'
      preLoaderRoute: typeof TackTransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$shopSlug': {
      id: '/s/$shopSlug'
      path: '/s/$shopSlug'
      fullPath: '/s/$shopSlug'
      preLoaderRoute: typeof SShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redigera/$shopId': {
      id: '/redigera/$shopId'
      path: '/redigera/$shopId'
      fullPath: '/redigera/$shopId'
      preLoaderRoute: typeof RedigeraShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SkapaRoute: SkapaRoute,
  RedigeraShopIdRoute: RedigeraShopIdRoute,
  SShopSlugRoute: SShopSlugRoute,
  TackTransactionIdRoute: TackTransactionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
